"""add links table

Revision ID: a2b0f8bfd1f5
Revises: 87eb8ffc3d9a
Create Date: 2021-01-12 22:11:45.627530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b0f8bfd1f5'
down_revision = '87eb8ffc3d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True, comment='名称'),
    sa.Column('url', sa.String(length=100), nullable=True, comment='链接地址'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_id'), 'links', ['id'], unique=False)
    op.create_table('options',
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_title', sa.String(length=50), nullable=True, comment='博客标题'),
    sa.Column('blog_sub_title', sa.String(length=100), nullable=True, comment='博客副标题'),
    sa.Column('about', sa.Text(), nullable=True, comment='关于'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_options_id'), 'options', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_options_id'), table_name='options')
    op.drop_table('options')
    op.drop_index(op.f('ix_links_id'), table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###
