"""blog v1

Revision ID: b313dc2447a6
Revises: 
Create Date: 2021-01-31 10:26:38.434938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b313dc2447a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True, comment='账号'),
    sa.Column('password_hash', sa.String(length=128), nullable=True, comment='密码'),
    sa.Column('blog_title', sa.String(length=60), nullable=True, comment='博客标题'),
    sa.Column('blog_sub_title', sa.String(length=100), nullable=True, comment='博客子标题'),
    sa.Column('name', sa.String(length=30), nullable=True, comment='作者名称'),
    sa.Column('about', sa.Text(), nullable=True, comment='关于'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_id'), 'admin', ['id'], unique=False)
    op.create_table('category',
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True, comment='分类名称'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table('post',
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True, comment='文章标题'),
    sa.Column('body', sa.Text(), nullable=True, comment='文章内容'),
    sa.Column('status', sa.Integer(), nullable=True, comment='文章状态,1 置顶显示 2正常显示 3 不显示'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类'),
    sa.Column('reading', sa.Integer(), nullable=True, comment='阅读量'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_id'), 'post', ['id'], unique=False)
    op.create_table('review',
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=30), nullable=True, comment='昵称'),
    sa.Column('pid', sa.Integer(), nullable=True, comment='父级评论ID'),
    sa.Column('post_id', sa.Integer(), nullable=True, comment='评论的文章'),
    sa.Column('content', sa.Text(), nullable=True, comment='评论内容'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_id'), 'review', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_post_id'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_admin_id'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
